### PR TITLE
Adding defualt var rds_engine

### PR DESCRIPTION
**Pull request by noqcks**
Adding a default var instead of waiting to fail out to realize you need to set `database_engine`. I set it to `rds_engine` to be more clear about the variable you are really setting.

### CODE REVIEW

**Comment by pdufault** [comment]
Looks awesome Ben. :rocket:

**Comment by killerwails** [comment]
why default to postgres?

**Comment by pdufault** [comment]
Why not postgres?  What alternative are you suggesting?

**Comment by killerwails** [comment]
im not suggesting, I just wondered why that. ¯\_(ツ)_/¯

**Comment by noqcks** [comment]
Just adding a sane default for the `rds_engine`. We have sane defaults for all other vars, I feel like it should be added for `rds_engine` as well. I could set it to `""` and then have `"{{ rds_engine | mandatory }}"` but I don't think that accomplishes anything.

**Comment by killerwails** [comment]
team reviewed. nikki approved

**Pull request merged**
