### PR TITLE
Fixing spot instances issue

### PR DESCRIPTION
**Pull request by noqcks**

### CODE REVIEW

**Comment by noqcks** [comment]
@killerwails @aaronpederson plz review

**Comment by killerwails** [comment]
Tested. This "fix" doesnt add the functionality you are expecting.

**Comment by noqcks** [comment]
@killerwails what does it do?

**Comment by killerwails** [comment]
it doesnt do anything. I tried spinning up a non-spot box in staging.....nothing happened

**Comment by killerwails** [comment]
my bad. does work.

**Comment by aaronpederson** [comment]
Team Approved

**Pull request merged**
